frr version 10.6.1
frr defaults traditional
hostname hz-edge2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.4.2/32
!
interface eth1
 ip address 198.18.2.7/31
!
interface eth2
 ip address 198.18.10.14/31
!
ip route 10.119.0.0/24 Null0
!
ip prefix-list RECURSIVE-NH-FIXTURE seq 10 permit 10.119.0.0/24
!
route-map SET-RECURSIVE-NH permit 10
 match ip address prefix-list RECURSIVE-NH-FIXTURE
 set ip next-hop 10.119.2.2
!
route-map SET-RECURSIVE-NH permit 20
!
router bgp 65004
 timers bgp 1 3
 bgp router-id 10.255.4.2
 no bgp ebgp-requires-policy
 neighbor 198.18.10.15 remote-as 65100
 neighbor 198.18.2.6 remote-as 65004
 !
 address-family ipv4 unicast
  network 10.119.0.0/24
  neighbor 198.18.10.15 activate
  neighbor 198.18.10.15 next-hop-self
  neighbor 198.18.2.6 activate
  neighbor 198.18.2.6 next-hop-self
  neighbor 198.18.2.6 route-map SET-RECURSIVE-NH out
 exit-address-family
exit
!
line vty
