frr version 10.6.1
frr defaults traditional
hostname dc3-external
service integrated-vtysh-config
!
interface eth1
!
interface eth2
 ip address 198.51.100.3/31
!
interface eth3
 ip address 198.51.100.4/31
!
ip route 10.203.0.0/16 Null0
!
ip prefix-list LOCAL-AGG seq 10 permit 10.203.0.0/16
ip prefix-list DC-AGG seq 10 permit 10.201.0.0/16
ip prefix-list DC-AGG seq 20 permit 10.202.0.0/16
ip prefix-list DC-AGG seq 30 permit 10.203.0.0/16
!
route-map LOCAL-AGG permit 10
 match ip address prefix-list LOCAL-AGG
!
route-map DC-AGG permit 10
 match ip address prefix-list DC-AGG
!
router bgp 4200000030
 bgp router-id 10.203.0.254
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as 4200000031
 !
 address-family ipv4 unicast
  redistribute ospf route-map DC-AGG
 exit-address-family
exit
!
router ospf
 ospf router-id 10.203.0.254
 passive-interface eth1
 network 198.51.100.2/31 area 0.0.0.0
 network 198.51.100.4/31 area 0.0.0.0
 redistribute static route-map LOCAL-AGG
exit
!
line vty
