table inet BLOCK_HTTP_TO_HZ {
  chain forward {
    type filter hook forward priority 0; policy accept;

    oifname "eth1" ip protocol tcp ip daddr 10.4.0.0/16 tcp dport 80 drop
    oifname "eth2" ip protocol tcp ip daddr 10.4.0.0/16 tcp dport 80 drop
  }
}
