frr version 10.6.1
frr defaults traditional
hostname dc1-client2
service integrated-vtysh-config
!
ip prefix-list VM-PREFIXES seq 10 permit 10.201.2.0/24 le 32
!
route-map VM-PREFIXES permit 10
 match ip address prefix-list VM-PREFIXES
!
router bgp 4200002012
 bgp router-id 10.201.255.2
 no bgp ebgp-requires-policy
 ! eth1 -> dc1-leaf2:e1-1
 neighbor eth1 interface remote-as 4200001012
 !
 address-family ipv4 unicast
  neighbor eth1 activate
  redistribute connected route-map VM-PREFIXES
 exit-address-family
exit
!
line vty
