frr version 10.6.1
frr defaults traditional
hostname bj-edge1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.1.1/32
!
interface eth1
 ip address 198.18.1.0/31
!
interface eth2
 ip address 198.18.2.0/31
!
interface eth3
 ip address 198.18.10.0/31
!
ip route 10.1.0.0/16 Null0
!
ip prefix-list LOCAL seq 10 permit any
!
route-map TAG-BJ-LOCAL permit 10
 match ip address prefix-list LOCAL
 set community 65001:100 additive
!
router bgp 65001
 timers bgp 1 3
 bgp router-id 10.255.1.1
 no bgp ebgp-requires-policy
 neighbor 198.18.2.1 remote-as 65001
 neighbor 198.18.10.1 remote-as 65100
 neighbor 198.18.1.1 remote-as 4200001001
 !
 address-family ipv4 unicast
  network 10.1.0.0/16
  neighbor 198.18.2.1 activate
  neighbor 198.18.2.1 next-hop-self
  neighbor 198.18.10.1 activate
  neighbor 198.18.10.1 next-hop-self
  neighbor 198.18.10.1 send-community
  neighbor 198.18.10.1 route-map TAG-BJ-LOCAL out
  neighbor 198.18.1.1 activate
  neighbor 198.18.1.1 next-hop-self
 exit-address-family
exit
!
line vty
