frr version 10.6.1
frr defaults traditional
hostname gz-edge2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.3.2/32
!
interface eth1
 ip address 198.18.2.5/31
!
interface eth2
 ip address 198.18.10.10/31
!
!
router bgp 65003
 bgp router-id 10.255.3.2
 no bgp ebgp-requires-policy
 neighbor 198.18.10.11 remote-as 65100
 neighbor 198.18.2.4 remote-as 65003
 !
 address-family ipv4 unicast
  neighbor 198.18.10.11 activate
  neighbor 198.18.10.11 next-hop-self
  neighbor 198.18.2.4 activate
  neighbor 198.18.2.4 next-hop-self
 exit-address-family
exit
!
line vty
