frr version 10.6.1
frr defaults traditional
hostname cust-sh
service integrated-vtysh-config
!
interface lo
 ip address 10.2.1.10/32
!
interface eth1
 ip address 198.18.1.3/31
!
ip route 10.2.1.10/32 Null0
!
ip prefix-list LOCAL seq 10 permit any
!
router bgp 4200001002
 bgp router-id 10.2.1.10
 no bgp ebgp-requires-policy
 neighbor 198.18.1.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.2.1.10/32
  neighbor 198.18.1.2 activate
  neighbor 198.18.1.2 next-hop-self
 exit-address-family
exit
!
line vty
