frr version 10.6.1
frr defaults traditional
hostname bj-edge2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.1.2/32
!
interface eth1
 ip address 198.18.2.1/31
!
interface eth2
 ip address 198.18.10.2/31
!
!
router bgp 65001
 bgp router-id 10.255.1.2
 no bgp ebgp-requires-policy
 neighbor 198.18.2.0 remote-as 65001
 neighbor 198.18.10.3 remote-as 65100
 !
 address-family ipv4 unicast
  neighbor 198.18.2.0 activate
  neighbor 198.18.2.0 next-hop-self
  neighbor 198.18.10.3 activate
  neighbor 198.18.10.3 next-hop-self
 exit-address-family
exit
!
line vty
