frr version 10.6.1
frr defaults traditional
hostname core-hz
service integrated-vtysh-config
!
interface lo
 ip address 10.255.100.4/32
!
interface eth1
 ip address 198.18.10.13/31
 ip access-group BLOCK-HTTP-TO-HZ out
!
interface eth2
 ip address 198.18.10.15/31
 ip access-group BLOCK-HTTP-TO-HZ out
!
interface eth3
 ip address 198.18.20.5/31
!
interface eth4
 ip address 198.18.20.6/31
!
interface eth5
 ip address 198.18.20.11/31
!
interface eth6
 ip address 198.18.30.6/31
!
ip prefix-list HZ-LOCAL seq 10 permit 10.4.0.0/16 le 32
!
ip access-list BLOCK-HTTP-TO-HZ
 seq 10 deny tcp any 10.4.0.0/16 eq 80
 seq 20 permit ip any any
!
route-map HZ-TRANSIT-OUT permit 10
 match ip address prefix-list HZ-LOCAL
 set metric +7
 set as-path prepend 65100 65100
 set origin incomplete
!
route-map HZ-TRANSIT-OUT permit 20
!
!
router bgp 65100
 timers bgp 1 3
 bgp router-id 10.255.100.4
 no bgp ebgp-requires-policy
 neighbor 198.18.20.7 remote-as 65100
 neighbor 198.18.20.4 remote-as 65100
 neighbor 198.18.20.10 remote-as 65100
 neighbor 198.18.10.12 remote-as 65004
 neighbor 198.18.10.14 remote-as 65004
 neighbor 198.18.30.7 remote-as 65200
 !
 address-family ipv4 unicast
  neighbor 198.18.20.7 activate
  neighbor 198.18.20.7 next-hop-self
  neighbor 198.18.20.4 activate
  neighbor 198.18.20.4 next-hop-self
  neighbor 198.18.20.10 activate
  neighbor 198.18.20.10 next-hop-self
  neighbor 198.18.10.12 activate
  neighbor 198.18.10.12 next-hop-self
  neighbor 198.18.10.14 activate
  neighbor 198.18.10.14 next-hop-self
  neighbor 198.18.30.7 activate
  neighbor 198.18.30.7 next-hop-self
  neighbor 198.18.30.7 route-map HZ-TRANSIT-OUT out
 exit-address-family
exit
!
line vty
