frr version 10.6.1
frr defaults traditional
hostname dc1-client1
service integrated-vtysh-config
!
ip prefix-list VM-PREFIXES seq 10 permit 10.201.1.0/24 le 32
!
route-map VM-PREFIXES permit 10
 match ip address prefix-list VM-PREFIXES
!
router bgp 4200002011
 bgp router-id 10.201.255.1
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as 4200001011
 !
 address-family ipv4 unicast
  neighbor eth1 activate
  redistribute connected route-map VM-PREFIXES
 exit-address-family
exit
!
line vty
